feat: enriches issuer and verifier sites
c4dt/eid-demo pull request #5
Opened 2024-01-29 11:40 UTC by lanterno

This has the improved websites that I've showed you this morning.  It implements the first item in [this ticket](https://github.com/c4dt/eid-demo/issues/2) 
It doesn't include the logging feature.

2024-01-29 12:49 UTC, PascalinDe commented on components/notImplemented.vue
> +      <p class="md:text-lg lg:text-xl text-gray-600 mt-8">We under your curiosity but this page is not necessary for the demo, thus it was not implemented.</p>
```suggestion
      <p class="md:text-lg lg:text-xl text-gray-600 mt-8">We understand your curiosity but this page is not necessary for the demo, thus it was not implemented.</p>
```

2024-01-29 12:59 UTC, PascalinDe commented on pages/issuer/index.vue
> +            This platform provides different activities for EPFL HR department.
```suggestion
            This platform provides different activities for ACME HR department.
```

2024-01-29 12:59 UTC, PascalinDe commented on pages/verifier/index.vue
> +            This platform provides different activities for EPFL HR department.
```suggestion
            This platform provides different activities for ACME HR department.
```

2024-01-29 13:00 UTC, PascalinDe commented on layouts/epfl.vue
> +                  <img class="w-24" src="https://c4dt.epfl.ch/wp-content/themes/epfl/assets/svg/epfl-logo.svg?color=indigo&shade=500" alt="Your Company" />
change this to other logo

2024-01-29 13:00 UTC, PascalinDe commented on pages/issuer/index.vue
> +            <p class="text-4xl font-semibold tracking-widest text-g uppercase">EPFL HR system</p>  for graduate affairs
```suggestion
            <p class="text-4xl font-semibold tracking-widest text-g uppercase">ACME HR system</p>  for graduate affairs
```

2024-01-30 12:48 UTC, ineiti requested changes
There are still some references to `epfl` in the code, for completeness you can change them to `acme`.

I would also put the svg-files into a separate directory instead of inlining them. This helps when reading the code: if I see `acme-logo.svg` or `acme-logo.png`, I know what image is there. If I see the svg-path, I have no idea...

2024-01-30 12:48 UTC, ineiti commented on pages/issuer/index.vue
> +    description: 'Manage the issuance of certificates upon request by students.\n' +
```suggestion
    description: 'Issue certificates upon request by students.\n' +
```

2024-01-30 13:31 UTC, lanterno commented
@PascalinDe @ineiti I  removed all mentions of EPFL (except the schema name. we can create a new schema later with a different name) 

I also applied the other minor fixed (typos and SVGs moved to separate files always)

2024-01-30 13:33 UTC, PascalinDe approved these changes

2024-02-01 11:05 UTC, merged